<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<SonarQubeExclude>true</SonarQubeExclude>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Dapper" Version="2.0.123" />
		<PackageReference Include="Dapper.FluentMap.Dommel" Version="2.0.0" />
		<PackageReference Include="Dommel" Version="3.0.0" />
		<PackageReference Include="Npgsql" Version="9.0.4" />
		<PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SME.Acessos.Aplicacao\SME.Acessos.Aplicacao.csproj" />
		<ProjectReference Include="..\SME.Acessos.Infra.Dominio\SME.Acessos.Infra.Dominio.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Microsoft.Extensions.Options">
			<HintPath>..\..\..\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.16\Microsoft.Extensions.Options.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
