<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SME.Acessos.Aplicacao\SME.Acessos.Aplicacao.csproj" />
    <ProjectReference Include="..\SME.Acessos.Infra.Dados\SME.Acessos.Infra.Dados.csproj" />
    <ProjectReference Include="..\SME.Acessos.Infra\SME.Acessos.Infra.Servicos.csproj" />
  </ItemGroup>

</Project>
