<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>592f5cac-c031-4142-9363-704fb9859767</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Apm.NetCoreAll" Version="1.22.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SME.Acessos.Aplicacao\SME.Acessos.Aplicacao.csproj" />
    <ProjectReference Include="..\SME.Acessos.IoC\SME.Acessos.IoC.csproj" />
  </ItemGroup>

</Project>
